Update node version to v12
버전이 너무 오래 되어 에러가 발생합니다.

airesearch:~/environment/serverless-crawler $ node handler.test.js
/home/ec2-user/node_modules/got/dist/source/create.js:131
    got.paginate = (async function* (url, options) {
                                  ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ec2-user/node_modules/got/dist/source/index.js:7:18)
airesearch:~/environment/serverless-crawler $ nvm install v12.16.2
Downloading https://nodejs.org/dist/v12.16.2/node-v12.16.2-linux-x64.tar.xz...
####################################################################################################################################################################################################### 100.0%
Now using node v12.16.2 (npm v6.14.4)
airesearch:~/environment/serverless-crawler $ node handler.test.js
success